feat_cols = [
 'season_Otoño',
    'season_Primavera',
    'season_Verano',
    'DayCount',
    'DayCount^2',
    'Tip_Bar Tradicional',
    'Tip_Cervecería',
    'Tip_Discoteca',
    'Tip_Establecimiento de Tapeo',
    'Tip_No Segmentado',
    'Tip_Noche Temprana',
    'Tip_Pastelería/Cafetería/Panadería',
    'Tip_Restaurante',
    'Tip_Restaurante de Imagen',
    'Tip_Restaurante de Imagen con Tapeo',
    'Orig_OFFLINE',
    'Type_Porcentual',
    'CouponDiscountAmt',
    'CouponDiscountAmt_LAG_1',
    'CouponDiscountAmt_LAG_2',
    'CouponDiscountAmt_LAG_3',
    'CouponDiscountAmt_LAG_4',
    'CouponDiscountAmt_LAG_5',
    'CouponDiscountAmt^2',
    'CouponDiscountAmt_LAG_1_POLY_2',
    'CouponDiscountAmt_LAG_2_POLY_2',
    'CouponDiscountAmt_LAG_3_POLY_2',
    'CouponDiscountAmt_LAG_4_POLY_2',
    'CouponDiscountAmt_LAG_5_POLY_2',
    'Sellout_LAG_1',
    'Sellout_LAG_2',
    'Sellout_LAG_3',
    'Sellout_LAG_4',
    'Sellout_LAG_5',
    'Sellout_LAG_1_POLY_2',
    'Sellout_LAG_2_POLY_2',
    'Sellout_LAG_3_POLY_2',
    'Sellout_LAG_4_POLY_2',
    'Sellout_LAG_5_POLY_2', 
  
]
